<?php
/**
 * The Header template for our theme
 *
 * Displays all of the <head> section and everything up till <div id="main">
 *
 * @package WordPress
 * @subpackage Twenty_Twelve
 * @since Twenty Twelve 1.0
 */
?><!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
<html <?php language_attributes(); ?>>
<!--<![endif]-->
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>" />
<meta name="viewport" content="width=device-width" />
<title><?php wp_title( '|', true, 'right' ); ?></title>
<link rel="profile" href="http://gmpg.org/xfn/11" />
<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>" />


<script src="https://use.fontawesome.com/762c66dd2b.js"></script>
<link href="https://fonts.googleapis.com/css?family=Oxygen|Source+Sans+Pro:300,400" rel="stylesheet">
<script defer src="<?php bloginfo( 'template_url' ); ?>/assets/svg-with-js/js/fontawesome-all.js"></script>

<link rel="apple-touch-icon" sizes="180x180" href="<?php bloginfo('template_url'); ?>/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" href="<?php bloginfo('template_url'); ?>/favicons/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="<?php bloginfo('template_url'); ?>/favicons/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="<?php bloginfo('template_url'); ?>/favicons/manifest.json">
<link rel="mask-icon" href="<?php bloginfo('template_url'); ?>/favicons/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">
<meta name="p:domain_verify" content="829ccd403f67421fa2ee9a5f56c6eea6"/>



<?php // Loads HTML5 JavaScript file to add support for HTML5 elements in older IE versions. ?>
<!--[if lt IE 9]>
<script src="<?php echo get_template_directory_uri(); ?>/js/html5.js" type="text/javascript"></script>
<![endif]-->

<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');

fbq('init', '1107124109368587');
fbq('track', "PageView");</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=1107124109368587&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->
<link href="https://fonts.googleapis.com/css?family=Arimo" rel="stylesheet">
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Bellaworks Web Design",
  "image" : "https://bellaworksweb.com/bw/wp-content/themes/bellaworks2017/images/logo-new.png",
  "telephone" : "(704) 375-0831",
  "email" : "info@bellaworksweb.com",
  "address" : {
    "@type" : "PostalAddress",
    "streetAddress" : "220 East Blvd #200a",
    "addressLocality" : "Charlotte",
    "addressRegion" : "North Carolina",
    "addressCountry" : "United States",
    "postalCode" : "28203"
  },
  "url" : "https://bellaworksweb.com/",
  "sameAs": [
    "http://www.facebook.com/bellaworks",
    "https://www.linkedin.com/company/1060900",
    "https://www.pinterest.com/bellaworksweb/pins/"
  ]
  
}
</script>

<?php wp_head(); ?>
</head>

<body class="preload">
<div id="skrollr-body"></div>
<div itemscope itemtype="http://schema.org/LocalBusiness" id="page" class="hfeed site">

  <div class=" " id="topwrap">
    <div class="wrapper">
      <header id="masthead" class="site-header" role="banner">
        <?php if(is_home()) { ?>
          <h1 class="logo" itemprop="image" itemscope itemtype="http://schema.org/ImageObject">
            <a href="<?php bloginfo('url'); ?>">
              <img src="<?php bloginfo('template_url'); ?>/images/bellaworks.png" itemprop="url" alt="Bellaworks - Web Design">
            </a>
          </h1>
        <?php } else { ?>
          <div class="logo" itemprop="image" itemscope itemtype="http://schema.org/ImageObject" alt="Bellaworks - Web Design">
            <a href="<?php bloginfo('url'); ?>">
              <img src="<?php bloginfo('template_url'); ?>/images/bellaworks.png" itemprop="url">
            </a>
          </div>
        <?php } ?>
        <div class="header-right">
        <?php 
          $address = get_field('address','option'); 
          $city = get_field('city','option');
          $state = get_field('state','option');
          $zip = get_field('zip','option');
          $year = date('Y');
          $phone = get_field('phone_number','option');
          $fax = get_field('fax','option');
        ?>
          
          <div class="teleephone">
            <a href="tel:<?php echo preg_replace('/[^0-9]/',"",$phone);?>">
              <span itemprop="telephone"><?php echo $phone ?></span>
              </a>
          </div><!-- phone -->


          <nav id="site-navigation" class="main-navigation" role="navigation">
            <button class="menu-toggle" aria-controls="primary-menu" aria-expanded="false"><?php esc_html_e( 'MENU', 'acstarter' ); ?></button>
            <?php wp_nav_menu( array( 'theme_location' => 'primary', 'menu_id' => 'primary-menu' ) ); ?>
          </nav><!-- #site-navigation -->

          

        </div><!-- header right -->
      </header><!-- #masthead -->
    </div><!-- wrapper -->
  </div><!-- top wrap -->
   

	
<?php if ( is_page('news') ) {
		$pageClass = 'bgcolor-beige';
	} else {
		$pageClass = 'bgcolor-grey';
	}
	?>
<div id="main" class="<?php echo $pageClass; ?>">